import 'package:flutter/material.dart';

class Variable{
  Color headercolor = Color(0xD510446d);
  Color fontcolor = Color(0xffffffff);
  List< Map<String,dynamic> > question = [
    {"question":"Near a pedestrian crossing,when the pedestrians are waiting to cross the road, you should",
      "answer":"Stop the vehicle and wait till the pedestrians cross the road and then proceed",
      "a":"gesagaf",
      "b":"Stop the vehicle and wait till the pedestrians cross the road and then proceed",
      "c":"gesagaf",
      "sign":false},
    {"question":"You are approaching an arrow bridge, another vehicle is about to enter the bridge from opposite side you should",
      "answer":"Wait till the other vehicle crosses the bridge and then proceed",
      "a":"fgfg",
      "b":"gesagaf",
      "c":"Wait till the other vehicle crosses the bridge and then proceed",
      "sign":false},
    {"question":"You can overtake a vehicle in front",
      "answer":"Through the left side, if the road is wide",
      "a":"Through the left side, if the road is wide",
      "b":"gesagaf",
      "c":"gesagaf",
      "sign":false},
    {"question":"Free passage should be given to the following types of vehicles ",
      "answer":"Express, Super Express buses",
      "a":"Express, Super Express buses",
      "b":"gesagaf",
      "c":"gesagaf",
      "sign":false},
    {"question":"Vehicles proceeding from opposite direction should be allowed to pass through ….",
      "answer":"The convenient side",
      "a":"gesagaf",
      "b":"gesagaf",
      "c":"The convenient side",
      "sign":false},
    {"question":"Driver of a vehicle may overtake … ",
      "answer":"When the driver of the vehicle in front shows the signal to overtake",
      "a":"gesagaf",
      "b":"When the driver of the vehicle in front shows the signal to overtake",
      "c":"gesagaf",
      "sign":false},
    {"question":"When a Vehicle is parked on the road side during night ",
      "answer":"The park light shall remain lit",
      "a":"The park light shall remain lit",
      "b":"gesagaf",
      "c":"gesagaf",
      "sign":false},
    {"question":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3u8wCTCC7Ws_R6JMytGzAkN2ZIQw4tw82fg&usqp=CAU",
      "answer":"Stop",
      "a":"gesagaf",
      "b":"gesagaf",
      "c":"Stop",
      "sign":true},
    {"question":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCZh_R6qdaEhCy5C0cUC2uPW3adFr05v37FA&usqp=CAU",
      "answer":"don`t turn right",
      "a":"don`t turn right",
      "b":"gesagaf",
      "c":"gesagaf",
      "sign":true},
    {"question":"https://5.imimg.com/data5/SH/WT/MY-152348/u-turn-prohibited-mandatory-retro-reflective-road-signage-500x500.jpg",
      "answer":"U turn",
      "a":"gesagaf",
      "b":"U turn",
      "c":"gesagaf",
      "sign":true},
    {"question":"https://d2m3nfprmhqjvd.cloudfront.net/blog/20220228141513/s24-1160x653.jpg",
      "answer":"One Side",
      "a":"One Side",
      "b":"gesagaf",
      "c":"gesagaf",
      "sign":true},
  ];
}